<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SukuCadang;

class SukuCadangSeeder extends Seeder
{
    public function run()
    {
        $sukuCadangList = [
            ['kode' => 'OLI001', 'nama' => 'Oli Mesin'],
            ['kode' => 'KMP002', 'nama' => 'Kampas Rem'],
            ['kode' => 'BUS003', 'nama' => 'Busi'],
            ['kode' => 'AKI004', 'nama' => 'Aki Motor'],
            ['kode' => 'FLT005', 'nama' => 'Filter Udara'],
            ['kode' => 'BAN006', 'nama' => 'Ban'],
            ['kode' => 'RNT007', 'nama' => 'Rantai'],
            ['kode' => 'SHK008', 'nama' => 'Shockbreaker'],
            ['kode' => 'SPR009', 'nama' => 'Spion'],
            ['kode' => 'KLX010', 'nama' => 'Knalpot Racing'],
            ['kode' => 'PST011', 'nama' => 'Piston'],
            ['kode' => 'KPG012', 'nama' => 'Kopling'],
            ['kode' => 'GSP013', 'nama' => 'Gasket Pack'],
            ['kode' => 'BLT014', 'nama' => 'Baut Mesin'],
            ['kode' => 'LCB015', 'nama' => 'Lampu Cabang'],
            ['kode' => 'CHN016', 'nama' => 'Rantai Motor'],
            ['kode' => 'SWT017', 'nama' => 'Switch Rem'],
            ['kode' => 'SPR018', 'nama' => 'Spring Standar'],
            ['kode' => 'FRK019', 'nama' => 'Fork Depan'],
            ['kode' => 'FND020', 'nama' => 'Fender'],
            ['kode' => 'HRN021', 'nama' => 'Klakson'],
            ['kode' => 'SPD022', 'nama' => 'Speedometer'],
            ['kode' => 'STN023', 'nama' => 'Standar Tengah'],
            ['kode' => 'FLM024', 'nama' => 'Flasher Lampu'],
            ['kode' => 'TSL025', 'nama' => 'Throttle Sensor'],
            ['kode' => 'CDI026', 'nama' => 'CDI Unit'],
            ['kode' => 'TMS027', 'nama' => 'Thermostat'],
            ['kode' => 'INJ028', 'nama' => 'Injector'],
            ['kode' => 'ECM029', 'nama' => 'ECM Unit'],
            ['kode' => 'ABS030', 'nama' => 'ABS Sensor'],
            ['kode' => 'TIR031', 'nama' => 'Inner Tube'],
            ['kode' => 'CVT032', 'nama' => 'V-Belt CVT'],
            ['kode' => 'TNS033', 'nama' => 'Tensioner Rantai'],
            ['kode' => 'STB034', 'nama' => 'Stabilizer'],
            ['kode' => 'DMP035', 'nama' => 'Damper Karet'],
            ['kode' => 'CLP036', 'nama' => 'Caliper Rem'],
            ['kode' => 'RCB037', 'nama' => 'Radiator Cap'],
            ['kode' => 'RDS038', 'nama' => 'Radiator Selang'],
            ['kode' => 'PMP039', 'nama' => 'Pompa Bensin'],
            ['kode' => 'STT040', 'nama' => 'Starter Motor'],
            ['kode' => 'MFL041', 'nama' => 'Magnet Flywheel'],
            ['kode' => 'STG042', 'nama' => 'Stang Motor'],
            ['kode' => 'TLG043', 'nama' => 'Tali Gas'],
            ['kode' => 'TLK044', 'nama' => 'Tali Kopling'],
            ['kode' => 'RIM045', 'nama' => 'Velg Motor'],
            ['kode' => 'FRT046', 'nama' => 'Friksi Kopling'],
            ['kode' => 'MCU047', 'nama' => 'Master Cylinder'],
            ['kode' => 'SCD048', 'nama' => 'Sekring Dasar'],
            ['kode' => 'HTP049', 'nama' => 'Headlamp'],
            ['kode' => 'BKR050', 'nama' => 'Brake Pad'],
            ['kode' => 'SLH051', 'nama' => 'Selang Bensin'],
            ['kode' => 'CIL052', 'nama' => 'Silinder Head'],
            ['kode' => 'CMP053', 'nama' => 'Camshaft'],
            ['kode' => 'FTL054', 'nama' => 'Filter Oli'],
            ['kode' => 'THM055', 'nama' => 'Thermistor'],
            ['kode' => 'FBR056', 'nama' => 'Fiber Body'],
            ['kode' => 'GBS057', 'nama' => 'Gigi Besar'],
            ['kode' => 'GRP058', 'nama' => 'Grip Stang'],
            ['kode' => 'CHM059', 'nama' => 'Chamber Knalpot'],
            ['kode' => 'MSH060', 'nama' => 'Muffler'],
            ['kode' => 'GSP061', 'nama' => 'Gasket Knalpot'],
            ['kode' => 'TLR062', 'nama' => 'Tail Light'],
            ['kode' => 'EXH063', 'nama' => 'Exhaust Pipe'],
            ['kode' => 'SHC064', 'nama' => 'Shock Cover'],
            ['kode' => 'RDC065', 'nama' => 'Radiator Coolant'],
            ['kode' => 'SPD066', 'nama' => 'Spark Plug'],
            ['kode' => 'PNL067', 'nama' => 'Panel Indikator'],
            ['kode' => 'STB068', 'nama' => 'Stator Coil'],
            ['kode' => 'TMC069', 'nama' => 'Timing Chain'],
            ['kode' => 'SPL070', 'nama' => 'Sprocket'],
            ['kode' => 'HND071', 'nama' => 'Handle Rem'],
            ['kode' => 'GSC072', 'nama' => 'Gasket Cover'],
            ['kode' => 'OTL073', 'nama' => 'Oli Transmisi'],
            ['kode' => 'MUD074', 'nama' => 'Mud Guard'],
            ['kode' => 'DRM075', 'nama' => 'Drum Brake'],
            ['kode' => 'SNR076', 'nama' => 'Sinar Lampu'],
            ['kode' => 'BUL077', 'nama' => 'Baut Roda'],
            ['kode' => 'JRP078', 'nama' => 'Jari-Jari Roda'],
            ['kode' => 'BRL079', 'nama' => 'Bearing Roda'],
            ['kode' => 'SND080', 'nama' => 'Sendal Kick Starter'],
            ['kode' => 'FRT081', 'nama' => 'Friksi Kanvas'],
            ['kode' => 'BWP082', 'nama' => 'Body Work Panel'],
            ['kode' => 'RMT083', 'nama' => 'Remote Alarm'],
            ['kode' => 'SLM084', 'nama' => 'Selang Oli'],
            ['kode' => 'PRT085', 'nama' => 'Protector Cover'],
            ['kode' => 'PNH086', 'nama' => 'Panel Headlamp'],
            ['kode' => 'SPK087', 'nama' => 'Speaker'],
            ['kode' => 'TMB088', 'nama' => 'Tombol Klakson'],
            ['kode' => 'JPN089', 'nama' => 'Jepitan Rem'],
            ['kode' => 'CNS090', 'nama' => 'Console Box'],
            ['kode' => 'BTR091', 'nama' => 'Baterai'],
            ['kode' => 'CLT092', 'nama' => 'Coolant Tank'],
            ['kode' => 'WRH093', 'nama' => 'Wrench Set'],
            ['kode' => 'STW094', 'nama' => 'Steering Wheel'],
            ['kode' => 'PNL095', 'nama' => 'Panel Speed'],
            ['kode' => 'BNC096', 'nama' => 'Bensin Cap'],
            ['kode' => 'HLD097', 'nama' => 'Holder Stang'],
            ['kode' => 'BRG098', 'nama' => 'Bearing'],
            ['kode' => 'SWT099', 'nama' => 'Switch ON/OFF'],
            ['kode' => 'MRR100', 'nama' => 'Mirror Set']
        ];

        foreach ($sukuCadangList as $item) {
            SukuCadang::create([
                'kode_suku_cadang' => $item['kode'],
                'nama_suku_cadang' => $item['nama']
            ]);
        }
    }
}
